admin.dashboard:
    pattern: /admin/
    defaults: { _controller: CmsBundle:AdminDashboard:index }

admin.login:
    pattern: /admin/login
    defaults: { _controller: CmsBundle:AdminSecurity:login }

admin.login_check:
    pattern: /admin/login_check

logout:
    pattern: /admin/logout

main:
    pattern:  /
    defaults: { _controller: CmsBundle:Legacy:index }

_legacy:
    pattern:  /{path}
    defaults: { _controller: CmsBundle:Legacy:index }
    requirements:
        path: ".+"
