admin.dashboard:
    pattern: /admin/
    defaults: { _controller: CmsBundle:AdminDashboard:index }

login:
    pattern: /login
    defaults: { _controller: CmsBundle:AdminSecurity:login }

login_check:
    pattern: /login_check

main:
    pattern:  /
    defaults: { _controller: CmsBundle:Legacy:index }

_legacy:
    pattern:  /{path}
    defaults: { _controller: CmsBundle:Legacy:index }
    requirements:
        path: ".+"
